stages:
  - build
  - deploy

include:
- project: "grayscale/ci/gitlab-templates"
  file: "templates/.base-terraform-template.yml"

build:
  extends: .base-terraform
  stage: build
  script:
    - script/build
  rules:
    - when: always
  tags:
    - $ENV_TYPE
  artifacts:
    paths:
    - terraform/.terraform

deploy:
  extends: .base-terraform
  stage: deploy
  variables:
    TF_CLI_ARGS_apply: "-auto-approve"
  script:
    - script/deploy "terraform"
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_REF_NAME == "main"
  tags:
    - $ENV_TYPE
