#!/usr/bin/env bash

# script/build: Run the test suite.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Linting Terraform code…"
terraform fmt -recursive -check

echo "==> Linting Packer code…"
packer fmt -recursive -check .

echo "==> Validating Packer templates…"
packer validate \
	-var-file=packer/environments/non-prod.pkrvars.hcl \
	packer/engineering-workstation.pkr.hcl
